AllCops:
  Exclude:
    - "vendor/**/*"
    - "lib/generators/*/notifier/templates/*"
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Exclude:
    - "outbox-rails.gemspec"
  IgnoreCopDirectives: true
  Max: 100

Metrics/MethodLength:
  Max: 15
